logging.level.org.springframework.cloud.kubernetes: DEBUG
spring.application.name: supermanservice

management:
  endpoint:
    restart:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health